kind = "api"
  previewPath = "/api"
  title = "API Server"
  version = "1.0.0"
  id = "3B4_FFSkEVBkAeYMFRJ2e"

  [[services]]
  localPort = 8080
  name = "API Server"
  paths = ["/api", "/__clerk"]

  [services.development]
  run = "pnpm --filter @workspace/api-server run dev"

  [services.env]
  PORT = "8080"
  BASE_PATH = "/"

  [services.production]
  run = "NODE_ENV=production node --enable-source-maps artifacts/api-server/dist/index.mjs"
  build = "sh -c 'NODE_ENV=production BASE_PATH=/ PORT=8080 pnpm --filter @workspace/canary-rentals run build && pnpm --filter @workspace/api-server run build'"

  [services.production.health.startup]
  path = "/api/healthz"
  